### ISSUE TITLE
Listening on specific host prints bogus URL in logs

### ISSUE THREAD

**Issue by elecnix** [messagebird/pushprom#4]
Specifying host to listen on prints:

```
$ pushprom -http-listen-address localhost:9091 -udp-listen-address localhost:9090
2016/11/10 17:04:43 http.go:36: exposing metrics on http://0.0.0.0:localhost:9091/metrics
2016/11/10 17:04:43 udp.go:10: listening for stats UDP on port localhost:9090
2016/11/10 17:04:43 http.go:39: listening for stats on http://0.0.0.0localhost:9091
```

Note the bogus http://0.0.0.0localhost:9091

**Comment by marcelcorso** [comment]
I think the problem is that the flags -udp-listen-address and -http-listen-address expect only port numbers and not full addresses. 
We can fix this two ways: fix the docs or try to detect if the user input is a port number or an address. 

here is how prometheus does it:
https://github.com/prometheus/prometheus/blob/6703404cb431f57ca4c5097bc2762438d3c1968e/cmd/prometheus/config.go#L300
it uses os.Hostname() to find out the address to bind to. 

For consistency, I think a good decision is to copy prometheus' behaviour.
